import { test, expect } from '../helpers/testFixtures.ts'
import { openTwitchChannel } from '../helpers/mockTwitch.ts'
import { waitForPulseRoot } from '../helpers/assertions.ts'

for (const placement of ['sidebar', 'right', 'bottom'] as const) {
  for (const density of ['comfortable', 'compact'] as const) {
    test(`${placement} ${density}: portrait artwork and reachable settings`, async ({ extension, prepare }, info) => {
      await extension.page.setViewportSize({ width: 1280, height: 600 })
      await prepare({ storage: { overlayPlacement: placement, densityPreference: density, overlayMode: 'expanded', sidebarTab: 'pulse' } })
      await openTwitchChannel(extension.page)
      await waitForPulseRoot(extension.page)
      const root = extension.page.locator('#streamclone-pulse-root')
      const artwork = root.locator('[data-games-played-item]').first()
      await expect(artwork).toBeVisible()
      const box = await artwork.boundingBox()
      expect(box!.height / box!.width).toBeGreaterThan(1.3)
      const settings = root.getByRole('button', { name: 'Open settings', exact: true })
      await expect(settings).toHaveCount(1)
      const footer = await settings.boundingBox()
      expect(footer!.y).toBeGreaterThanOrEqual(0)
      expect(footer!.y + footer!.height).toBeLessThanOrEqual(600)
      await extension.page.screenshot({ animations: 'disabled', path: info.outputPath('restored-surface.png') })
      await root.locator('.pulse-panel-body').evaluate(e => { e.scrollTop = e.scrollHeight })
      await expect(settings).toBeInViewport()
      await settings.click()
      await expect(root.getByRole('heading', { name: 'Quick settings' })).toBeVisible()
      await expect(root.getByRole('combobox', { name: 'Default chart range' })).toHaveCount(0)
      await root.getByRole('button', { name: 'Back to Pulse' }).click()
      const range = root.getByRole('combobox', { name: 'Chart time range' })
      await range.click()
      const menu = root.getByRole('listbox', { name: 'Chart time range' })
      await expect(menu).toBeVisible()
      expect(await range.evaluate(e => getComputedStyle(e).fontFamily)).toContain('Inter')
      expect(await menu.evaluate(e => getComputedStyle(e).fontFamily)).toContain('Inter')
      const menuBox = await menu.boundingBox()
      expect(menuBox!.y).toBeGreaterThanOrEqual(0)
      expect(menuBox!.y + menuBox!.height).toBeLessThanOrEqual(600)
      await extension.page.screenshot({ animations: 'disabled', path: info.outputPath('chart-range-menu.png') })
      await range.press('Escape')
      await expect(menu).toHaveCount(0)
      await expect(range).toBeFocused()
    })
  }
}

test('Emerald persists while each new chart starts on Full stream', async ({ extension, prepare }, info) => {
  await prepare({ storage: { overlayPlacement: 'sidebar', overlayMode: 'expanded', sidebarTab: 'pulse' } })
  await openTwitchChannel(extension.page)
  await waitForPulseRoot(extension.page)
  await extension.page.getByRole('button', { name: 'Open settings', exact: true }).click()
  await extension.page.getByRole('button', { name: 'Emerald', exact: true }).click()
  await expect(extension.page.locator('html')).toHaveAttribute('data-pulse-accent', 'emerald')
  await expect(extension.page.getByRole('combobox', { name: 'Default chart range' })).toHaveCount(0)
  await extension.page.getByRole('button', { name: 'Back to Pulse' }).click()
  const range = extension.page.getByRole('combobox', { name: 'Chart time range' })
  await range.click()
  await extension.page.getByRole('option', { name: '30 min', exact: true }).click()
  await expect(range).toContainText('30 min')
  await extension.page.reload()
  await waitForPulseRoot(extension.page)
  await expect(extension.page.locator('html')).toHaveAttribute('data-pulse-accent', 'emerald')
  await expect(range).toContainText('Full stream')
  const options = await extension.context.newPage()
  await options.goto(`chrome-extension://${extension.extensionId}/options/index.html#pulse`)
  await expect(options.getByRole('combobox', { name: 'Default chart range' })).toHaveCount(0)
  await expect(options.getByRole('button', { name: /Emerald/ })).toHaveAttribute('aria-pressed', 'true')
  await options.screenshot({ animations: 'disabled', path: info.outputPath('full-settings-emerald.png') })
  await options.getByRole('link', { name: 'Developer', exact: true }).click()
  const cadence = options.getByRole('combobox', { name: 'Polling cadence' })
  await cadence.click()
  await expect(options.getByRole('listbox')).toBeVisible()
  await expect(options.getByRole('listbox')).toHaveCSS('opacity', '1')
  const triggerBox = await cadence.boundingBox()
  const listBox = await options.getByRole('listbox').boundingBox()
  expect(Math.abs(listBox!.x + listBox!.width - triggerBox!.x - triggerBox!.width)).toBeLessThan(2)
  await cadence.press('Home')
  await cadence.press('ArrowDown')
  await cadence.press('Enter')
  await expect(cadence).toContainText('30s')
})

test('spikes use contrasting symbols and preserve interaction', async ({ extension, prepare }, info) => {
  await prepare({ storage: { overlayPlacement: 'sidebar', overlayMode: 'expanded', sidebarTab: 'pulse' } })
  await openTwitchChannel(extension.page)
  await waitForPulseRoot(extension.page)
  await extension.page.getByRole('button', { name: 'Show spike markers', exact: true }).click()
  const marker = extension.page.locator('[data-spike-symbol="diamond"]').first()
  await expect(marker).toBeVisible()
  await expect(marker).toHaveAttribute('fill', '#fbbf24')
  await expect(marker).toHaveAttribute('stroke', '#111117')
  await extension.page.screenshot({ animations: 'disabled', path: info.outputPath('spike-symbols.png') })
  const hit = marker.locator('..')
  await hit.focus()
  await hit.press('Enter')
  await expect(extension.page.locator('[aria-label^="Selected moment at"]').first()).toBeVisible()
})

for (const placement of ['right', 'bottom'] as const) {
  test(placement + ' mini dock opens settings', async ({ extension, prepare }) => {
    await prepare({ storage: { overlayPlacement: placement, overlayMode: 'mini' } })
    await openTwitchChannel(extension.page)
    await waitForPulseRoot(extension.page)
    await extension.page.getByRole('button', { name: 'Open settings', exact: true }).click()
    await expect(extension.page.getByRole('heading', { name: 'Quick settings' })).toBeVisible()
  })
}
